-------------------------------------------------------------------------------
-- Title          : Wishbone slave core for FOFB CC registers
-------------------------------------------------------------------------------
-- File           : fofb_cc_csr.vhdl
-- Author         : auto-generated by wbgen2 from fofb_cc_csr.wb
-- Created        : Fri Nov 06 16:14:42 2020
-- Standard       : VHDL'87
-------------------------------------------------------------------------------
-- THIS FILE WAS GENERATED BY wbgen2 FROM SOURCE FILE fofb_cc_csr.wb
-- DO NOT HAND-EDIT UNLESS IT'S ABSOLUTELY NECESSARY!
-------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.wbgen2_pkg.all;

entity fofb_cc_csr is
  port (
    rst_n_i              : in    std_logic;
    clk_sys_i            : in    std_logic;
    wb_adr_i             : in    std_logic_vector(11 downto 0);
    wb_dat_i             : in    std_logic_vector(31 downto 0);
    wb_dat_o             : out   std_logic_vector(31 downto 0);
    wb_cyc_i             : in    std_logic;
    wb_sel_i             : in    std_logic_vector(3 downto 0);
    wb_stb_i             : in    std_logic;
    wb_we_i              : in    std_logic;
    wb_ack_o             : out   std_logic;
    wb_stall_o           : out   std_logic;
    fofb_cc_clk_ram_reg_i : in    std_logic;
    -- Ports for RAM: FOFB CC RAM for register map
    fofb_cc_csr_ram_reg_addr_i : in    std_logic_vector(10 downto 0);
    -- Read data output
    fofb_cc_csr_ram_reg_data_o : out   std_logic_vector(31 downto 0);
    -- Read strobe input (active high)
    fofb_cc_csr_ram_reg_rd_i : in    std_logic;
    -- Write data input
    fofb_cc_csr_ram_reg_data_i : in    std_logic_vector(31 downto 0);
    -- Write strobe (active high)
    fofb_cc_csr_ram_reg_wr_i : in    std_logic;
    -- Port for None field: 'Dummy register' in reg: 'Dummy register'
    fofb_cc_csr_dummy_o  : out   std_logic_vector(31 downto 0)
  );
end fofb_cc_csr;

architecture syn of fofb_cc_csr is

  signal fofb_cc_csr_ram_reg_rddata_int : std_logic_vector(31 downto 0);
  signal fofb_cc_csr_ram_reg_rd_int     : std_logic;
  signal fofb_cc_csr_ram_reg_wr_int     : std_logic;
  signal fofb_cc_csr_dummy_int          : std_logic_vector(31 downto 0);
  signal ack_sreg                       : std_logic_vector(9 downto 0);
  signal rddata_reg                     : std_logic_vector(31 downto 0);
  signal wrdata_reg                     : std_logic_vector(31 downto 0);
  signal bwsel_reg                      : std_logic_vector(3 downto 0);
  signal rwaddr_reg                     : std_logic_vector(11 downto 0);
  signal ack_in_progress                : std_logic;
  signal wr_int                         : std_logic;
  signal rd_int                         : std_logic;
  signal allones                        : std_logic_vector(31 downto 0);
  signal allzeros                       : std_logic_vector(31 downto 0);

begin
  -- Some internal signals assignments. For (foreseen) compatibility with other bus standards.
  wrdata_reg <= wb_dat_i;
  bwsel_reg <= wb_sel_i;
  rd_int <= wb_cyc_i and (wb_stb_i and (not wb_we_i));
  wr_int <= wb_cyc_i and (wb_stb_i and wb_we_i);
  allones <= (others => '1');
  allzeros <= (others => '0');
  -- 
  -- Main register bank access process.
  process (clk_sys_i, rst_n_i)
  begin
    if (rst_n_i = '0') then
      ack_sreg <= "0000000000";
      ack_in_progress <= '0';
      rddata_reg <= "00000000000000000000000000000000";
      fofb_cc_csr_dummy_int <= "00000000000000000000000000000000";
    elsif rising_edge(clk_sys_i) then
      -- advance the ACK generator shift register
      ack_sreg(8 downto 0) <= ack_sreg(9 downto 1);
      ack_sreg(9) <= '0';
      if (ack_in_progress = '1') then
        if (ack_sreg(0) = '1') then
          ack_in_progress <= '0';
        else
        end if;
      else
        if ((wb_cyc_i = '1') and (wb_stb_i = '1')) then
          case rwaddr_reg(11) is
          when '0' =>
            case rwaddr_reg(11 downto 0) is
            when "100000000000" =>
              if (wb_we_i = '1') then
                fofb_cc_csr_dummy_int <= wrdata_reg(31 downto 0);
              end if;
              rddata_reg(31 downto 0) <= fofb_cc_csr_dummy_int;
              ack_sreg(0) <= '1';
              ack_in_progress <= '1';
            when others =>
              -- prevent the slave from hanging the bus on invalid address
              ack_in_progress <= '1';
              ack_sreg(0) <= '1';
            end case;
          when '1' =>
            if (rd_int = '1') then
              ack_sreg(0) <= '1';
            else
              ack_sreg(0) <= '1';
            end if;
            ack_in_progress <= '1';
          when others =>
            -- prevent the slave from hanging the bus on invalid address
            ack_in_progress <= '1';
            ack_sreg(0) <= '1';
          end case;
        end if;
      end if;
    end if;
  end process;


  -- Data output multiplexer process
  process (rddata_reg, rwaddr_reg, fofb_cc_csr_ram_reg_rddata_int, wb_adr_i  )
  begin
    case rwaddr_reg(11) is
    when '1' =>
      wb_dat_o(31 downto 0) <= fofb_cc_csr_ram_reg_rddata_int;
    when others =>
      wb_dat_o <= rddata_reg;
    end case;
  end process;


  -- Read & write lines decoder for RAMs
  process (wb_adr_i, rd_int, wr_int  )
  begin
    if (wb_adr_i(11) = '1') then
      fofb_cc_csr_ram_reg_rd_int <= rd_int;
      fofb_cc_csr_ram_reg_wr_int <= wr_int;
    else
      fofb_cc_csr_ram_reg_wr_int <= '0';
      fofb_cc_csr_ram_reg_rd_int <= '0';
    end if;
  end process;


  -- extra code for reg/fifo/mem: FOFB CC RAM for register map
  -- RAM block instantiation for memory: FOFB CC RAM for register map
  fofb_cc_csr_ram_reg_raminst: wbgen2_dpssram
    generic map (
      g_data_width         => 32,
      g_size               => 2048,
      g_addr_width         => 11,
      g_dual_clock         => true,
      g_use_bwsel          => false
    )
    port map (
      clk_a_i              => clk_sys_i,
      clk_b_i              => fofb_cc_clk_ram_reg_i,
      addr_b_i             => fofb_cc_csr_ram_reg_addr_i,
      addr_a_i             => rwaddr_reg(10 downto 0),
      data_b_o             => fofb_cc_csr_ram_reg_data_o,
      rd_b_i               => fofb_cc_csr_ram_reg_rd_i,
      data_b_i             => fofb_cc_csr_ram_reg_data_i,
      wr_b_i               => fofb_cc_csr_ram_reg_wr_i,
      bwsel_b_i            => allones(3 downto 0),
      data_a_o             => fofb_cc_csr_ram_reg_rddata_int(31 downto 0),
      rd_a_i               => fofb_cc_csr_ram_reg_rd_int,
      data_a_i             => wrdata_reg(31 downto 0),
      wr_a_i               => fofb_cc_csr_ram_reg_wr_int,
      bwsel_a_i            => allones(3 downto 0)
    );
  
  -- Dummy register
  fofb_cc_csr_dummy_o <= fofb_cc_csr_dummy_int;
  rwaddr_reg <= wb_adr_i;
  wb_stall_o <= (not ack_sreg(0)) and (wb_stb_i and wb_cyc_i);
  -- ACK signal generation. Just pass the LSB of ACK counter.
  wb_ack_o <= ack_sreg(0);
end syn;
