








# <xdcgen_start>

# This section has been generated automatically by xdcgen.py. Do not hand-modify if not really necessary.
# Command used: ./xdcgen.py -c afc-v4-1hpc-1lpc-rtm-variant -m 0:fmc-4sfp+-caen-v1 afcv4_fmc_4sfp+_caen.xdc
# xdcgen pin assignments for mezzanine fmc-4sfp+-caen-v1 slot 0
set_property PACKAGE_PIN F13 [get_ports fmc0_sfp_rx_p_i[0]]
set_property PACKAGE_PIN E13 [get_ports fmc0_sfp_rx_n_i[0]]
set_property PACKAGE_PIN D16 [get_ports fmc0_sfp_rx_p_i[1]]
set_property PACKAGE_PIN C16 [get_ports fmc0_sfp_rx_n_i[1]]
set_property PACKAGE_PIN F17 [get_ports fmc0_sfp_rx_p_i[2]]
set_property PACKAGE_PIN E17 [get_ports fmc0_sfp_rx_n_i[2]]
set_property PACKAGE_PIN F15 [get_ports fmc0_sfp_rx_p_i[3]]
set_property PACKAGE_PIN E15 [get_ports fmc0_sfp_rx_n_i[3]]
set_property PACKAGE_PIN B13 [get_ports fmc0_sfp_tx_p_o[0]]
set_property PACKAGE_PIN A13 [get_ports fmc0_sfp_tx_n_o[0]]
set_property PACKAGE_PIN B15 [get_ports fmc0_sfp_tx_p_o[1]]
set_property PACKAGE_PIN A15 [get_ports fmc0_sfp_tx_n_o[1]]
set_property PACKAGE_PIN B17 [get_ports fmc0_sfp_tx_p_o[2]]
set_property PACKAGE_PIN A17 [get_ports fmc0_sfp_tx_n_o[2]]
set_property PACKAGE_PIN D14 [get_ports fmc0_sfp_tx_p_o[3]]
set_property PACKAGE_PIN C14 [get_ports fmc0_sfp_tx_n_o[3]]
set_property PACKAGE_PIN M7 [get_ports fmc0_sfp_scl_b[0]]
set_property IOSTANDARD LVCMOS25 [get_ports fmc0_sfp_scl_b[0]]
set_property PACKAGE_PIN M6 [get_ports fmc0_sfp_sda_b[0]]
set_property IOSTANDARD LVCMOS25 [get_ports fmc0_sfp_sda_b[0]]
set_property PACKAGE_PIN M5 [get_ports fmc0_sfp_scl_b[1]]
set_property IOSTANDARD LVCMOS25 [get_ports fmc0_sfp_scl_b[1]]
set_property PACKAGE_PIN M4 [get_ports fmc0_sfp_sda_b[1]]
set_property IOSTANDARD LVCMOS25 [get_ports fmc0_sfp_sda_b[1]]
set_property PACKAGE_PIN M11 [get_ports fmc0_sfp_scl_b[2]]
set_property IOSTANDARD LVCMOS25 [get_ports fmc0_sfp_scl_b[2]]
set_property PACKAGE_PIN M10 [get_ports fmc0_sfp_sda_b[2]]
set_property IOSTANDARD LVCMOS25 [get_ports fmc0_sfp_sda_b[2]]
set_property PACKAGE_PIN N3 [get_ports fmc0_sfp_scl_b[3]]
set_property IOSTANDARD LVCMOS25 [get_ports fmc0_sfp_scl_b[3]]
set_property PACKAGE_PIN N2 [get_ports fmc0_sfp_sda_b[3]]
set_property IOSTANDARD LVCMOS25 [get_ports fmc0_sfp_sda_b[3]]
set_property PACKAGE_PIN K2 [get_ports fmc0_sfp_mod_abs_i[0]]
set_property IOSTANDARD LVCMOS25 [get_ports fmc0_sfp_mod_abs_i[0]]
set_property PACKAGE_PIN K3 [get_ports fmc0_sfp_mod_abs_i[1]]
set_property IOSTANDARD LVCMOS25 [get_ports fmc0_sfp_mod_abs_i[1]]
set_property PACKAGE_PIN K5 [get_ports fmc0_sfp_mod_abs_i[2]]
set_property IOSTANDARD LVCMOS25 [get_ports fmc0_sfp_mod_abs_i[2]]
set_property PACKAGE_PIN L5 [get_ports fmc0_sfp_mod_abs_i[3]]
set_property IOSTANDARD LVCMOS25 [get_ports fmc0_sfp_mod_abs_i[3]]
set_property PACKAGE_PIN H3 [get_ports fmc0_sfp_rx_los_i[0]]
set_property IOSTANDARD LVCMOS25 [get_ports fmc0_sfp_rx_los_i[0]]
set_property PACKAGE_PIN H4 [get_ports fmc0_sfp_rx_los_i[1]]
set_property IOSTANDARD LVCMOS25 [get_ports fmc0_sfp_rx_los_i[1]]
set_property PACKAGE_PIN J1 [get_ports fmc0_sfp_rx_los_i[2]]
set_property IOSTANDARD LVCMOS25 [get_ports fmc0_sfp_rx_los_i[2]]
set_property PACKAGE_PIN K1 [get_ports fmc0_sfp_rx_los_i[3]]
set_property IOSTANDARD LVCMOS25 [get_ports fmc0_sfp_rx_los_i[3]]
set_property PACKAGE_PIN J3 [get_ports fmc0_sfp_tx_disable_o[0]]
set_property IOSTANDARD LVCMOS25 [get_ports fmc0_sfp_tx_disable_o[0]]
set_property PACKAGE_PIN J4 [get_ports fmc0_sfp_tx_disable_o[1]]
set_property IOSTANDARD LVCMOS25 [get_ports fmc0_sfp_tx_disable_o[1]]
set_property PACKAGE_PIN F2 [get_ports fmc0_sfp_tx_disable_o[2]]
set_property IOSTANDARD LVCMOS25 [get_ports fmc0_sfp_tx_disable_o[2]]
set_property PACKAGE_PIN F3 [get_ports fmc0_sfp_tx_disable_o[3]]
set_property IOSTANDARD LVCMOS25 [get_ports fmc0_sfp_tx_disable_o[3]]
set_property PACKAGE_PIN G1 [get_ports fmc0_sfp_tx_fault_i[0]]
set_property IOSTANDARD LVCMOS25 [get_ports fmc0_sfp_tx_fault_i[0]]
set_property PACKAGE_PIN H1 [get_ports fmc0_sfp_tx_fault_i[1]]
set_property IOSTANDARD LVCMOS25 [get_ports fmc0_sfp_tx_fault_i[1]]
set_property PACKAGE_PIN G6 [get_ports fmc0_sfp_tx_fault_i[2]]
set_property IOSTANDARD LVCMOS25 [get_ports fmc0_sfp_tx_fault_i[2]]
set_property PACKAGE_PIN G7 [get_ports fmc0_sfp_tx_fault_i[3]]
set_property IOSTANDARD LVCMOS25 [get_ports fmc0_sfp_tx_fault_i[3]]
set_property PACKAGE_PIN L2 [get_ports fmc0_sfp_rs0_o[0]]
set_property IOSTANDARD LVCMOS25 [get_ports fmc0_sfp_rs0_o[0]]
set_property PACKAGE_PIN M2 [get_ports fmc0_sfp_rs0_o[1]]
set_property IOSTANDARD LVCMOS25 [get_ports fmc0_sfp_rs0_o[1]]
set_property PACKAGE_PIN G2 [get_ports fmc0_sfp_rs0_o[2]]
set_property IOSTANDARD LVCMOS25 [get_ports fmc0_sfp_rs0_o[2]]
set_property PACKAGE_PIN H2 [get_ports fmc0_sfp_rs0_o[3]]
set_property IOSTANDARD LVCMOS25 [get_ports fmc0_sfp_rs0_o[3]]
set_property PACKAGE_PIN G9 [get_ports fmc0_sfp_rs1_o[0]]
set_property IOSTANDARD LVCMOS25 [get_ports fmc0_sfp_rs1_o[0]]
set_property PACKAGE_PIN G10 [get_ports fmc0_sfp_rs1_o[1]]
set_property IOSTANDARD LVCMOS25 [get_ports fmc0_sfp_rs1_o[1]]
set_property PACKAGE_PIN K8 [get_ports fmc0_sfp_rs1_o[2]]
set_property IOSTANDARD LVCMOS25 [get_ports fmc0_sfp_rs1_o[2]]
set_property PACKAGE_PIN L8 [get_ports fmc0_sfp_rs1_o[3]]
set_property IOSTANDARD LVCMOS25 [get_ports fmc0_sfp_rs1_o[3]]
set_property PACKAGE_PIN H16 [get_ports fmc0_si570_clk_p_i]
set_property PACKAGE_PIN G16 [get_ports fmc0_si570_clk_n_i]
set_property PACKAGE_PIN N8 [get_ports fmc0_si570_scl_b]
set_property IOSTANDARD LVCMOS25 [get_ports fmc0_si570_scl_b]
set_property PACKAGE_PIN N7 [get_ports fmc0_si570_sda_b]
set_property IOSTANDARD LVCMOS25 [get_ports fmc0_si570_sda_b]
# <xdcgen_end>
