name: Run all testbenches
on:
  push:
    branches:
      - master
      - devel
  pull_request:

jobs:
  run_testbenches:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lnls-dig/gw-tb-toolchain:latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Run testbenches
        run: cd hdl/testbench && ./test-all.sh
